language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  # PHPUnit tests
  - vendor/bin/phpunit

after_success:

notifications:
  slack: rulemailer:uNKX4aotYlORokPax7NUEIL2
  email: zion.developer@gmail.com
#Multi-channel notification
#   notifications:
#    slack:
#      rooms:
#        - rulemailer:uNKX4aotYlORokPax7NUEIL2#general
#        - rulemailer:uNKX4aotYlORokPax7NUEIL2#random